name: t_virus
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Custom CheckBox
  circular_check_box:
  # FlushBar is used to advise user
  flushbar:
  # Get the lat and log of the user
  geolocator:
  # HTTP Cliient
  dio: ^3.0.9
  # Database
  sqflite:
  # Bottom Navigator for the main screen
  circular_bottom_navigation:
  # Maps for the main traker screen
  google_maps_flutter:
  maps_launcher:
  map_launcher:
  # For the lauch icons
  flutter_launcher_icons:
  cupertino_icons: ^0.1.3


flutter_icons:
  image_path: "images/ic_launch_zombie.png"
  android: true
  ios: true

flutter_launcher_name:
  name: "T-Virus"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/styles/

  fonts:
    - family: ZOMBIE
      fonts:
        - asset: assets/fonts/zombie_font.TTF
    - family: ZOMBIETEXT
      fonts:
        - asset: assets/fonts/zombie_texts.TTF

